apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: {{ template "redis.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
status: {}