name: nginx-ingress-controller
version: 0.0.1
home: "https://github.com/tracing-app/backend"
maintainers:
  - name: "Amrit Baveja"
    email: "amrit_baveja@branson.org"
dependencies:
  - name: ingress-nginx
    version: "2.15.0"
    repository: "https://kubernetes.github.io/ingress-nginx"