apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "admin-oidc.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: admin.marintracingapp.org
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "admin-oidc.fullname" . }}
          servicePort: {{ .Values.exposePort }}