apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ template "neo4j.fullname" . }}
  labels:
    name: {{ template "neo4j.fullname" . }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
    - name: "bolt"
      port: 7687
      targetPort: {{ .Values.exposePort }}
    - name: "https"
      port: 7473
      targetPort: {{ .Values.httpsExposePort }}
  selector:
    name: {{ template "neo4j.fullname" . }}
status:
  loadBalancer: {}
