apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "rest.fullname" . }}
  labels:
    name: {{ template "rest.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      name: {{ template "rest.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "rest.fullname" . }}
      creationTimestamp: null
    spec:
      initContainers:
        - name: wait-for-vault-service
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-vault; do sleep 1.5; echo "Waiting for Vault to start..."; done']
      containers:
      - env:
        - name: VAULT_ADDRESS
          value: https://{{ .Release.Name }}-vault
        - name: REDIS_ADDRESS
          value: redis://{{ .Release.Name }}-redis
        - name: VAULT_ROLE
          value: {{ .Values.vault.vaultRole }}
        image: gcr.io/vault-159468/rest:{{ .Values.imageVersion }}
        name: {{ template "rest.fullname" .}}
        ports:
          - containerPort: {{ .Values.exposePort }}
        {{ if eq .Values.readinessProbe.enabled "true" }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelay }}
          periodSeconds: {{ .Values.readinessProbe.interval}}
        {{ end }}
        {{ if eq .Values.livenessProbe.enabled "true" }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelay }}
          periodSeconds: {{ .Values.livenessProbe.interval }}
        {{ end }}
      restartPolicy: Always
      serviceAccountName: {{ template "rest.fullname" . }}-serviceaccount
      imagePullSecrets:
      - name: gcp-registry
status: {}